# Generated by Django 5.2.7 on 2025-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sign',
            field=models.CharField(default='empy', max_length=255),
            preserve_default=False,
        ),
    ]
