# Generated by Django 5.2.7 on 2025-10-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sign',
        ),
    ]
